//! Desktop-native streamed downloads.
//!
//! Network bytes never enter the webview. Rust validates the requested API URL
//! against the invoking webview, reuses its authentication cookies, refuses
//! redirects, streams into a same-directory temporary file, and renames only
//! after a complete response. Cancellation and every error remove the temp.
//! SPA-generated bytes cross Tauri IPC as cooperative JSON chunks. Tauri
//! materializes and parses each complete frame before Rust checks its length, so
//! the check rejects contract violations but does not cap IPC allocation.

use std::collections::HashMap;
use std::ffi::OsStr;
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex, OnceLock};
use std::time::{Duration, SystemTime};

use futures::StreamExt;
use serde::Serialize;
use tauri::WebviewWindow;
use tokio::io::AsyncWriteExt;

use crate::native_transfer::{
    endpoint_for_window, http_client, request_headers, EndpointKind, TransferRegistration,
};

/// Cooperative SPA/Rust wire limit for a generated-download JSON chunk.
///
/// Tauri materializes and parses the complete IPC frame before command dispatch,
/// so this rejects an oversized chunk after allocation rather than preventing it.
const GENERATED_CHUNK_LIMIT: usize = 64 * 1024;

#[derive(Debug, Serialize)]
pub struct SavedDownload {
    pub path: String,
}

struct DownloadTarget {
    temp: PathBuf,
    target: PathBuf,
    committed: bool,
}

impl DownloadTarget {
    async fn create(filename: &str) -> Result<(Self, tokio::fs::File), String> {
        let safe = sanitize_filename(filename);
        let (dir, target) = tokio::task::spawn_blocking(move || {
            let dir = downloads_dir()
                .ok_or_else(|| "could not resolve a Downloads folder".to_string())?;
            std::fs::create_dir_all(&dir)
                .map_err(|error| format!("creating {}: {error}", dir.display()))?;
            let target = dir.join(safe);
            Ok::<_, String>((dir, target))
        })
        .await
        .map_err(|error| format!("preparing native download target: {error}"))??;
        let temp = dir.join(format!(
            ".chan-download-{}-{}.tmp",
            std::process::id(),
            uuid::Uuid::new_v4()
        ));
        let file = tokio::fs::OpenOptions::new()
            .create_new(true)
            .write(true)
            .open(&temp)
            .await
            .map_err(|error| format!("creating {}: {error}", temp.display()))?;
        Ok((
            Self {
                temp,
                target,
                committed: false,
            },
            file,
        ))
    }

    async fn commit(mut self, mut file: tokio::fs::File) -> Result<SavedDownload, String> {
        file.flush()
            .await
            .map_err(|error| format!("flushing {}: {error}", self.temp.display()))?;
        file.sync_all()
            .await
            .map_err(|error| format!("syncing {}: {error}", self.temp.display()))?;
        drop(file);
        let temp = self.temp.clone();
        let requested = self.target.clone();
        let target = tokio::task::spawn_blocking(move || {
            let _commit = download_commit_lock()
                .lock()
                .map_err(|_| "native download commit lock poisoned".to_string())?;
            let directory = requested
                .parent()
                .ok_or_else(|| "native download target has no parent".to_string())?;
            let filename = requested
                .file_name()
                .and_then(|name| name.to_str())
                .ok_or_else(|| "native download target has no UTF-8 file name".to_string())?;
            let target = unique_path(directory, filename);
            std::fs::rename(&temp, &target).map_err(|error| {
                format!(
                    "committing {} to {}: {error}",
                    temp.display(),
                    target.display()
                )
            })?;
            Ok::<_, String>(target)
        })
        .await
        .map_err(|error| format!("joining native download commit: {error}"))??;
        self.target = target;
        self.committed = true;
        Ok(SavedDownload {
            path: self.target.display().to_string(),
        })
    }
}

impl Drop for DownloadTarget {
    fn drop(&mut self) {
        if !self.committed {
            let _ = std::fs::remove_file(&self.temp);
        }
    }
}

#[tauri::command]
pub async fn download_file_native(
    window: WebviewWindow,
    transfer_id: String,
    url: String,
    filename: String,
) -> Result<SavedDownload, String> {
    let endpoint = endpoint_for_window(&window, &url, EndpointKind::Download)?;
    let headers = request_headers(&window, &endpoint, false)?;
    let registration = TransferRegistration::new(transfer_id, None)?;
    let client = http_client()?;
    let request = client.get(endpoint).headers(headers).send();
    let response = tokio::select! {
        _ = registration.progress.cancelled() => return Err("download cancelled".into()),
        response = request => response.map_err(|error| format!("download request failed: {error}"))?,
    };
    if response.status().is_redirection() {
        return Err("download refused an unexpected redirect".into());
    }
    if !response.status().is_success() {
        return Err(response_error("download", response).await);
    }
    registration.progress.set_total(response.content_length());
    let (target, mut file) = DownloadTarget::create(&filename).await?;
    let mut body = response.bytes_stream();
    loop {
        let chunk = tokio::select! {
            _ = registration.progress.cancelled() => return Err("download cancelled".into()),
            chunk = body.next() => chunk,
        };
        let Some(chunk) = chunk else {
            break;
        };
        let chunk = chunk.map_err(|error| format!("reading download response: {error}"))?;
        file.write_all(&chunk)
            .await
            .map_err(|error| format!("writing {}: {error}", target.temp.display()))?;
        registration.progress.add_loaded(chunk.len() as u64);
    }
    if registration.progress.is_cancelled() {
        return Err("download cancelled".into());
    }
    target.commit(file).await
}

async fn response_error(kind: &str, response: reqwest::Response) -> String {
    let status = response.status();
    let mut detail = Vec::new();
    let mut stream = response.bytes_stream();
    while detail.len() < 512 {
        let Some(next) = stream.next().await else {
            break;
        };
        let Ok(bytes) = next else {
            break;
        };
        let remaining = 512 - detail.len();
        detail.extend_from_slice(&bytes[..bytes.len().min(remaining)]);
    }
    let detail = String::from_utf8_lossy(&detail);
    if detail.trim().is_empty() {
        format!("{kind} failed: HTTP {status}")
    } else {
        format!("{kind} failed: HTTP {status}: {}", detail.trim())
    }
}

struct GeneratedSink {
    // Field order is deliberate: cancellation drops the open handle before
    // DownloadTarget removes its temp, including on platforms that refuse to
    // unlink an open file.
    file: Option<tokio::fs::File>,
    target: DownloadTarget,
}

type SharedGeneratedSink = Arc<tokio::sync::Mutex<Option<GeneratedSink>>>;

struct RegisteredGeneratedSink {
    window_label: String,
    sink: SharedGeneratedSink,
}

fn generated_sinks() -> &'static Mutex<HashMap<String, RegisteredGeneratedSink>> {
    static SINKS: OnceLock<Mutex<HashMap<String, RegisteredGeneratedSink>>> = OnceLock::new();
    SINKS.get_or_init(|| Mutex::new(HashMap::new()))
}

fn generated_sink_for_window(
    handle: &str,
    window_label: &str,
) -> Result<SharedGeneratedSink, String> {
    let sinks = generated_sinks()
        .lock()
        .map_err(|_| "generated download registry poisoned".to_string())?;
    let registered = sinks
        .get(handle)
        .ok_or_else(|| "generated download handle is not active".to_string())?;
    if registered.window_label != window_label {
        return Err("generated download handle belongs to another window".to_string());
    }
    Ok(Arc::clone(&registered.sink))
}

fn take_generated_sink_for_window(
    handle: &str,
    window_label: &str,
) -> Result<SharedGeneratedSink, String> {
    let mut sinks = generated_sinks()
        .lock()
        .map_err(|_| "generated download registry poisoned".to_string())?;
    let registered = sinks
        .get(handle)
        .ok_or_else(|| "generated download handle is not active".to_string())?;
    if registered.window_label != window_label {
        return Err("generated download handle belongs to another window".to_string());
    }
    sinks
        .remove(handle)
        .map(|registered| registered.sink)
        .ok_or_else(|| "generated download handle is not active".to_string())
}

pub(crate) fn drop_generated_downloads_for_window(
    window_label: &str,
) -> tauri::async_runtime::JoinHandle<()> {
    let removed = match generated_sinks().lock() {
        Ok(mut sinks) => {
            let mut removed = Vec::new();
            sinks.retain(|_, registered| {
                if registered.window_label == window_label {
                    removed.push(Arc::clone(&registered.sink));
                    false
                } else {
                    true
                }
            });
            removed
        }
        Err(_) => {
            tracing::warn!(
                window_label,
                "generated download registry poisoned during window cleanup"
            );
            Vec::new()
        }
    };
    tauri::async_runtime::spawn(async move {
        for sink in removed {
            let generated = sink.lock().await.take();
            drop(generated);
        }
    })
}

fn download_commit_lock() -> &'static Mutex<()> {
    static COMMIT: Mutex<()> = Mutex::new(());
    &COMMIT
}

#[derive(Serialize)]
pub struct GeneratedDownloadHandle {
    handle: String,
}

#[tauri::command]
pub async fn begin_generated_download(
    window: WebviewWindow,
    filename: String,
) -> Result<GeneratedDownloadHandle, String> {
    let handle = uuid::Uuid::new_v4().simple().to_string();
    let (target, file) = DownloadTarget::create(&filename).await?;
    generated_sinks()
        .lock()
        .map_err(|_| "generated download registry poisoned".to_string())?
        .insert(
            handle.clone(),
            RegisteredGeneratedSink {
                window_label: window.label().to_string(),
                sink: Arc::new(tokio::sync::Mutex::new(Some(GeneratedSink {
                    file: Some(file),
                    target,
                }))),
            },
        );
    Ok(GeneratedDownloadHandle { handle })
}

#[tauri::command]
pub async fn append_generated_download(
    window: WebviewWindow,
    handle: String,
    bytes: Vec<u8>,
) -> Result<(), String> {
    if bytes.len() > GENERATED_CHUNK_LIMIT {
        return Err(format!(
            "generated download chunk exceeds {GENERATED_CHUNK_LIMIT} bytes"
        ));
    }
    let sink = generated_sink_for_window(&handle, window.label())?;
    let mut sink = sink.lock().await;
    let sink = sink
        .as_mut()
        .ok_or_else(|| "generated download handle is not active".to_string())?;
    sink.file
        .as_mut()
        .expect("active generated sink has a file")
        .write_all(&bytes)
        .await
        .map_err(|error| format!("writing {}: {error}", sink.target.temp.display()))
}

#[tauri::command]
pub async fn finish_generated_download(
    window: WebviewWindow,
    handle: String,
) -> Result<SavedDownload, String> {
    let sink = take_generated_sink_for_window(&handle, window.label())?;
    let mut sink = sink.lock().await;
    let mut sink = sink
        .take()
        .ok_or_else(|| "generated download handle is not active".to_string())?;
    let file = sink.file.take().expect("active generated sink has a file");
    sink.target.commit(file).await
}

#[tauri::command]
pub async fn cancel_generated_download(handle: String) -> bool {
    let sink = generated_sinks()
        .lock()
        .ok()
        .and_then(|mut sinks| sinks.remove(&handle))
        .map(|registered| registered.sink);
    let Some(sink) = sink else {
        return false;
    };
    sink.lock().await.take();
    true
}

pub(crate) fn downloads_dir() -> Option<PathBuf> {
    dirs::download_dir().or_else(dirs::home_dir)
}

fn generated_download_temp_pid(name: &OsStr) -> Option<u32> {
    let name = name.to_str()?;
    let body = name.strip_prefix(".chan-download-")?.strip_suffix(".tmp")?;
    let (pid_text, uuid_text) = body.split_once('-')?;
    if pid_text.is_empty() || !pid_text.bytes().all(|byte| byte.is_ascii_digit()) {
        return None;
    }
    let pid = pid_text.parse::<u32>().ok()?;
    if pid.to_string() != pid_text {
        return None;
    }
    let id = uuid::Uuid::parse_str(uuid_text).ok()?;
    if id.hyphenated().to_string() != uuid_text {
        return None;
    }
    Some(pid)
}

pub(crate) fn reap_orphaned_download_temps(
    dir: &Path,
    now: SystemTime,
    max_age: Duration,
) -> usize {
    let entries = match std::fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(error) => {
            tracing::warn!(
                directory = %dir.display(),
                error = %error,
                "reading Downloads directory for orphaned generated downloads failed"
            );
            return 0;
        }
    };
    let mut reaped = 0;
    for entry in entries {
        let entry = match entry {
            Ok(entry) => entry,
            Err(error) => {
                tracing::warn!(
                    directory = %dir.display(),
                    error = %error,
                    "reading a Downloads directory entry failed"
                );
                continue;
            }
        };
        let file_type = match entry.file_type() {
            Ok(file_type) => file_type,
            Err(error) => {
                tracing::warn!(
                    path = %entry.path().display(),
                    error = %error,
                    "reading a generated download temp file type failed"
                );
                continue;
            }
        };
        if !file_type.is_file() {
            continue;
        }
        let Some(pid) = generated_download_temp_pid(&entry.file_name()) else {
            continue;
        };
        if pid == std::process::id() {
            continue;
        }
        let modified = match entry.metadata().and_then(|metadata| metadata.modified()) {
            Ok(modified) => modified,
            Err(error) => {
                tracing::warn!(
                    path = %entry.path().display(),
                    error = %error,
                    "reading a generated download temp modification time failed"
                );
                continue;
            }
        };
        let Ok(age) = now.duration_since(modified) else {
            continue;
        };
        if age < max_age {
            continue;
        }
        let path = entry.path();
        match std::fs::remove_file(&path) {
            Ok(()) => reaped += 1,
            Err(error) => tracing::warn!(
                path = %path.display(),
                error = %error,
                "removing an orphaned generated download temp failed"
            ),
        }
    }
    reaped
}

fn sanitize_filename(filename: &str) -> String {
    let base = filename
        .rsplit(['/', '\\'])
        .next()
        .unwrap_or(filename)
        .trim();
    let cleaned: String = base
        .chars()
        .map(|character| {
            if character.is_control() {
                '_'
            } else {
                character
            }
        })
        .collect();
    if cleaned.is_empty() || matches!(cleaned.as_str(), "." | "..") {
        "download".to_string()
    } else {
        cleaned
    }
}

fn unique_path(dir: &Path, name: &str) -> PathBuf {
    let candidate = dir.join(name);
    if !candidate.exists() {
        return candidate;
    }
    let (stem, ext) = split_ext(name);
    for number in 1..=9999 {
        let alternative = match &ext {
            Some(ext) => format!("{stem} ({number}).{ext}"),
            None => format!("{stem} ({number})"),
        };
        let candidate = dir.join(alternative);
        if !candidate.exists() {
            return candidate;
        }
    }
    dir.join(format!("{stem}-{}", uuid::Uuid::new_v4()))
}

fn split_ext(name: &str) -> (String, Option<String>) {
    match name.rfind('.') {
        Some(index) if index > 0 && index < name.len() - 1 => (
            name[..index].to_string(),
            Some(name[index + 1..].to_string()),
        ),
        _ => (name.to_string(), None),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn desktop_download_never_buffers_the_network_response_over_ipc() {
        let rust = include_str!("download.rs");
        let production = rust
            .split("#[cfg(test)]")
            .next()
            .expect("production download module");
        let web = include_str!("../../../web/packages/workspace-app/src/api/desktop.ts");
        assert!(!production.contains("save_file_to_downloads"));
        assert!(!web.contains("responseType = \"arraybuffer\""));
        assert!(!web.contains("Array.from(bytes)"));
    }

    #[test]
    fn generated_chunk_limit_matches_the_spa_chunk_size() {
        let web = include_str!("../../../web/packages/workspace-app/src/api/desktop.ts");
        let expected = format!("{} * 1024", GENERATED_CHUNK_LIMIT / 1024);
        assert_eq!(
            web.matches(&expected).count(),
            2,
            "saveBytesToDownloads must chunk at GENERATED_CHUNK_LIMIT"
        );
        assert!(web.contains(&format!("offset += {expected}")));
        assert!(web.contains(&format!("offset + {expected}")));
    }

    #[test]
    fn sanitize_strips_path_separators() {
        assert_eq!(sanitize_filename("../../etc/passwd"), "passwd");
        assert_eq!(sanitize_filename("a/b/c.md"), "c.md");
        assert_eq!(sanitize_filename("plain.txt"), "plain.txt");
        assert_eq!(sanitize_filename(""), "download");
        assert_eq!(sanitize_filename("   "), "download");
        assert_eq!(sanitize_filename(".."), "download");
    }

    #[test]
    fn split_ext_handles_dotfiles_and_extensions() {
        assert_eq!(split_ext("a.md"), ("a".to_string(), Some("md".to_string())));
        assert_eq!(split_ext("noext"), ("noext".to_string(), None));
        assert_eq!(split_ext(".gitignore"), (".gitignore".to_string(), None));
    }

    #[test]
    fn unique_path_dedupes_against_existing() {
        let temp = tempfile::tempdir().unwrap();
        let first = unique_path(temp.path(), "note.md");
        assert_eq!(first, temp.path().join("note.md"));
        std::fs::write(&first, b"x").unwrap();
        let second = unique_path(temp.path(), "note.md");
        assert_eq!(second, temp.path().join("note (1).md"));
    }

    #[tokio::test]
    async fn uncommitted_download_target_removes_its_temp() {
        let temp = tempfile::tempdir().unwrap();
        let target = temp.path().join("out.bin");
        let staged = temp.path().join(".out.tmp");
        std::fs::write(&staged, b"partial").unwrap();
        drop(DownloadTarget {
            temp: staged.clone(),
            target,
            committed: false,
        });
        assert!(!staged.exists());
    }

    #[tokio::test]
    async fn generated_cancel_waits_for_an_in_flight_chunk_then_removes_its_temp() {
        let temp = tempfile::tempdir().unwrap();
        let target = temp.path().join("out.bin");
        let staged = temp.path().join(".out.tmp");
        let file = tokio::fs::File::create(&staged).await.unwrap();
        let handle = format!("cancel-race-{}", uuid::Uuid::new_v4());
        let sink = Arc::new(tokio::sync::Mutex::new(Some(GeneratedSink {
            file: Some(file),
            target: DownloadTarget {
                temp: staged.clone(),
                target,
                committed: false,
            },
        })));
        generated_sinks().lock().unwrap().insert(
            handle.clone(),
            RegisteredGeneratedSink {
                window_label: format!("cancel-window-{}", uuid::Uuid::new_v4()),
                sink: Arc::clone(&sink),
            },
        );

        let chunk_guard = sink.lock().await;
        let cancel = tokio::spawn(cancel_generated_download(handle.clone()));
        tokio::task::yield_now().await;
        assert!(
            staged.exists(),
            "cancel waits for the in-flight chunk lock instead of losing the handle"
        );
        drop(chunk_guard);

        assert!(cancel.await.unwrap());
        assert!(!staged.exists());
        assert!(!generated_sinks().lock().unwrap().contains_key(&handle));
    }

    #[tokio::test]
    async fn destroying_a_window_drops_only_that_windows_generated_sinks() {
        let temp = tempfile::tempdir().unwrap();
        let staged_a = temp.path().join(".a.tmp");
        let staged_b = temp.path().join(".b.tmp");
        let file_a = tokio::fs::File::create(&staged_a).await.unwrap();
        let file_b = tokio::fs::File::create(&staged_b).await.unwrap();
        let handle_a = format!("destroy-a-{}", uuid::Uuid::new_v4());
        let handle_b = format!("destroy-b-{}", uuid::Uuid::new_v4());
        let label_a = format!("workspace-a-{}", uuid::Uuid::new_v4());
        let label_b = format!("workspace-b-{}", uuid::Uuid::new_v4());
        let sink_a = Arc::new(tokio::sync::Mutex::new(Some(GeneratedSink {
            file: Some(file_a),
            target: DownloadTarget {
                temp: staged_a.clone(),
                target: temp.path().join("a.bin"),
                committed: false,
            },
        })));
        let sink_b = Arc::new(tokio::sync::Mutex::new(Some(GeneratedSink {
            file: Some(file_b),
            target: DownloadTarget {
                temp: staged_b.clone(),
                target: temp.path().join("b.bin"),
                committed: false,
            },
        })));
        {
            let mut sinks = generated_sinks().lock().unwrap();
            sinks.insert(
                handle_a.clone(),
                RegisteredGeneratedSink {
                    window_label: label_a.clone(),
                    sink: sink_a,
                },
            );
            sinks.insert(
                handle_b.clone(),
                RegisteredGeneratedSink {
                    window_label: label_b,
                    sink: sink_b,
                },
            );
        }

        drop_generated_downloads_for_window(&label_a).await.unwrap();

        assert!(!staged_a.exists());
        assert!(!generated_sinks().lock().unwrap().contains_key(&handle_a));
        assert!(staged_b.exists());
        assert!(generated_sinks().lock().unwrap().contains_key(&handle_b));
        assert!(cancel_generated_download(handle_b).await);
    }

    #[test]
    fn generated_handles_are_scoped_to_their_window() {
        let handle = format!("owned-{}", uuid::Uuid::new_v4());
        let label = format!("workspace-{}", uuid::Uuid::new_v4());
        let sink = Arc::new(tokio::sync::Mutex::new(None));
        generated_sinks().lock().unwrap().insert(
            handle.clone(),
            RegisteredGeneratedSink {
                window_label: label.clone(),
                sink: Arc::clone(&sink),
            },
        );

        assert!(generated_sink_for_window(&handle, "another-window").is_err());
        assert!(take_generated_sink_for_window(&handle, "another-window").is_err());
        assert!(generated_sinks().lock().unwrap().contains_key(&handle));
        let found = generated_sink_for_window(&handle, &label).unwrap();
        assert!(Arc::ptr_eq(&found, &sink));
        let removed = take_generated_sink_for_window(&handle, &label).unwrap();
        assert!(Arc::ptr_eq(&removed, &sink));
        assert!(!generated_sinks().lock().unwrap().contains_key(&handle));
    }

    #[test]
    fn generated_download_temp_parser_requires_canonical_minted_shape() {
        let id = uuid::Uuid::new_v4();
        let canonical = format!(".chan-download-42-{id}.tmp");
        assert_eq!(
            generated_download_temp_pid(OsStr::new(&canonical)),
            Some(42)
        );

        for decoy in [
            format!("chan-download-42-{id}.tmp"),
            format!(".chan-download-042-{id}.tmp"),
            format!(".chan-download-+42-{id}.tmp"),
            format!(".chan-download-42-{}.tmp", id.simple()),
            format!(
                ".chan-download-42-{}.tmp",
                id.to_string().to_ascii_uppercase()
            ),
            format!(".chan-download-42-{id}.tmp.backup"),
        ] {
            assert_eq!(
                generated_download_temp_pid(OsStr::new(&decoy)),
                None,
                "{decoy} is not a minted temp name"
            );
        }
    }

    #[test]
    fn startup_reap_removes_only_old_foreign_generated_download_temps() {
        let temp = tempfile::tempdir().unwrap();
        let current_pid = std::process::id();
        let foreign_pid = if current_pid == u32::MAX {
            current_pid - 1
        } else {
            current_pid + 1
        };
        let foreign = temp.path().join(format!(
            ".chan-download-{foreign_pid}-{}.tmp",
            uuid::Uuid::new_v4()
        ));
        let ours = temp.path().join(format!(
            ".chan-download-{current_pid}-{}.tmp",
            uuid::Uuid::new_v4()
        ));
        let bystander = temp.path().join("quarterly notes.md");
        let invalid_uuid = temp
            .path()
            .join(format!(".chan-download-{foreign_pid}-not-a-uuid.tmp"));
        let extra_suffix = temp.path().join(format!(
            ".chan-download-{foreign_pid}-{}.tmp.backup",
            uuid::Uuid::new_v4()
        ));
        let nested = temp.path().join("nested");
        std::fs::create_dir(&nested).unwrap();
        let matching_directory = temp.path().join(format!(
            ".chan-download-{foreign_pid}-{}.tmp",
            uuid::Uuid::new_v4()
        ));
        std::fs::create_dir(&matching_directory).unwrap();
        let nested_foreign = nested.join(format!(
            ".chan-download-{foreign_pid}-{}.tmp",
            uuid::Uuid::new_v4()
        ));
        for path in [
            &foreign,
            &ours,
            &bystander,
            &invalid_uuid,
            &extra_suffix,
            &nested_foreign,
        ] {
            std::fs::write(path, b"x").unwrap();
        }

        assert_eq!(
            reap_orphaned_download_temps(
                temp.path(),
                std::time::SystemTime::now(),
                std::time::Duration::from_secs(60 * 60),
            ),
            0
        );
        assert_eq!(
            reap_orphaned_download_temps(
                temp.path(),
                std::time::SystemTime::now(),
                std::time::Duration::ZERO,
            ),
            1
        );
        assert!(!foreign.exists());
        for path in [
            &ours,
            &bystander,
            &invalid_uuid,
            &extra_suffix,
            &matching_directory,
            &nested_foreign,
        ] {
            assert!(path.exists(), "{} must not be reaped", path.display());
        }
    }

    #[tokio::test]
    async fn concurrent_same_name_downloads_commit_without_overwriting() {
        let temp = tempfile::tempdir().unwrap();
        let requested = temp.path().join("same.bin");
        let staged_a = temp.path().join(".a.tmp");
        let staged_b = temp.path().join(".b.tmp");
        let mut file_a = tokio::fs::File::create(&staged_a).await.unwrap();
        let mut file_b = tokio::fs::File::create(&staged_b).await.unwrap();
        file_a.write_all(b"first").await.unwrap();
        file_b.write_all(b"second").await.unwrap();
        let target_a = DownloadTarget {
            temp: staged_a,
            target: requested.clone(),
            committed: false,
        };
        let target_b = DownloadTarget {
            temp: staged_b,
            target: requested,
            committed: false,
        };

        let (saved_a, saved_b) = tokio::join!(target_a.commit(file_a), target_b.commit(file_b));
        let saved_a = saved_a.unwrap().path;
        let saved_b = saved_b.unwrap().path;
        assert_ne!(saved_a, saved_b);
        let mut contents = [
            std::fs::read(saved_a).unwrap(),
            std::fs::read(saved_b).unwrap(),
        ];
        contents.sort();
        assert_eq!(contents, [b"first".to_vec(), b"second".to_vec()]);
    }
}
